package com.foldforge.studio.data.repository

import com.foldforge.studio.core.ai.GeneratedProject
import com.foldforge.studio.core.git.GitService
import com.foldforge.studio.core.model.ProjectType
import com.foldforge.studio.core.storage.Project
import com.foldforge.studio.core.storage.ProjectStore
import com.foldforge.studio.core.storage.ProjectSummary
import com.foldforge.studio.data.database.FoldForgeDatabase
import com.foldforge.studio.data.database.ProjectEntity
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.File
import java.io.InputStream

/**
 * Project list + lifecycle. The file system (`.foldforge/project.json`) is the source of truth;
 * Room mirrors it for ordering (recent/pinned) and fast queries. All IO runs on Dispatchers.IO.
 */
class ProjectRepository(
    private val store: ProjectStore,
    private val db: FoldForgeDatabase,
    private val scope: CoroutineScope,
) {
    private val _summaries = MutableStateFlow<List<ProjectSummary>>(emptyList())
    val summaries: StateFlow<List<ProjectSummary>> = _summaries.asStateFlow()
    private val _loading = MutableStateFlow(true)
    val loading: StateFlow<Boolean> = _loading.asStateFlow()

    fun refresh() {
        scope.launch(Dispatchers.IO) {
            val list = store.list()
            val opened = db.projects().run { list.associate { it.id to (get(it.id)?.lastOpenedAt ?: 0L) } }
            _summaries.value = list.sortedByDescending { maxOf(opened[it.id] ?: 0L, it.lastModified) }
            list.forEach { s ->
                if (db.projects().get(s.id) == null) {
                    db.projects().upsert(ProjectEntity(s.id, s.name, s.type.name, s.path, s.lastModified, 0L))
                }
            }
            _loading.value = false
        }
    }

    private suspend fun record(p: Project) {
        db.projects().upsert(ProjectEntity(p.id, p.meta.name, p.meta.type.name, p.root.absolutePath, p.meta.createdAt, System.currentTimeMillis()))
        refresh()
    }

    suspend fun create(name: String, templateId: String): Project = withContext(Dispatchers.IO) {
        store.createFromTemplate(name.trim().ifEmpty { "Untitled" }, templateId).also { record(it) }
    }

    /** Materialises an AI-generated project; Three.js projects receive the bundled vendor build. */
    suspend fun createFromAi(gen: GeneratedProject, vendorThree: ByteArray?): Project = withContext(Dispatchers.IO) {
        val type = when (gen.type.lowercase()) { "threejs" -> ProjectType.THREEJS; "html" -> ProjectType.HTML; else -> ProjectType.CANVAS }
        val files = gen.files.toMutableMap()
        if (!files.containsKey("README.md")) files["README.md"] = "# ${gen.name}\n\nGenerated by FOLD FORGE AI Build.\n"
        val p = store.createFromFiles(gen.name, type, gen.entry, files, "AI Build")
        if (vendorThree != null && files.values.any { it.contains("vendor/three.module.min.js") }) {
            p.fs.writeBytes("vendor/three.module.min.js", vendorThree)
        }
        record(p)
        p
    }

    suspend fun importZip(input: InputStream, name: String): Project = withContext(Dispatchers.IO) {
        store.importZip(input, name).also { record(it) }
    }

    suspend fun clone(url: String, token: String?): Project = withContext(Dispatchers.IO) {
        val repoName = url.trimEnd('/').substringAfterLast('/').removeSuffix(".git").ifEmpty { "repo" }
        val dir = store.newProjectDir(repoName)
        dir.delete()
        try {
            GitService.clone(url, dir, token)
        } catch (e: Exception) {
            dir.deleteRecursively()
            throw e
        }
        store.adoptDirectory(dir, repoName, "Cloned from $url").also { record(it) }
    }

    suspend fun open(id: String): Project = withContext(Dispatchers.IO) {
        store.open(id).also { db.projects().touch(id, System.currentTimeMillis()) }
    }

    suspend fun delete(id: String) = withContext(Dispatchers.IO) {
        store.delete(id)
        db.projects().delete(id)
        refresh()
    }

    fun exists(id: String) = store.exists(id)
    val workspace: File get() = store.workspace
}
